# Generated by Django 3.0.7 on 2020-06-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='flight_categories',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_category',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FlightCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_category', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHESTPRAC.Question')),
            ],
        ),
    ]
