# Generated by Django 3.0.7 on 2020-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0004_auto_20200615_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightcategories',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='flight_categories',
            field=models.ManyToManyField(to='EHESTPRAC.FlightCategories'),
        ),
    ]
