# Generated by Django 3.0.7 on 2020-06-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0005_auto_20200615_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='flight_categories',
            new_name='flight_category',
        ),
    ]
