# Generated by Django 3.0.7 on 2020-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0006_auto_20200615_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
