# Generated by Django 3.0.7 on 2020-06-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0007_choices_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcategories',
            name='category_name',
            field=models.CharField(default='This', max_length=30),
            preserve_default=False,
        ),
    ]
