# Generated by Django 3.0.7 on 2020-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0008_flightcategories_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=999),
        ),
    ]
