# Generated by Django 3.0.7 on 2020-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0009_question_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_order',
        ),
    ]
