# Generated by Django 3.0.7 on 2020-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHESTPRAC', '0010_remove_question_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(default=999),
        ),
    ]
